import type { Scenario, ScenarioId } from './simulatorTypes';

export const SCENARIOS: Record<ScenarioId, Scenario> = {
  jikoshoukai: {
    id: 'jikoshoukai',
    title_en: 'Self-Introduction',
    title_fr: 'Auto-présentation',
    subtitle_en: '自己紹介の練習',
    subtitle_fr: 'Pratiquer la自己紹介',
    description_en: 'Build and perfect your 2-minute 自己紹介 for Japanese job interviews. The AI guides you step by step through greeting, education, career, motivation, and closing.',
    description_fr: 'Construisez et perfectionnez votre 自己紹介 de 2 minutes pour les entretiens d\'embauche au Japon.',
    aiRole_en: 'Japanese Language Tutor',
    aiRole_fr: 'Tuteur de japonais',
    accentColor: 'cyan',
    icon: '🎯',
    hint_en: 'Start with: 「はじめまして、{name}と申します。」',
    hint_fr: 'Commencez par: 「はじめまして、{name}と申します。」',
  },
  interview: {
    id: 'interview',
    title_en: 'Interview Simulator',
    title_fr: 'Simulateur d\'entretien',
    subtitle_en: '面接の練習',
    subtitle_fr: 'Pratiquer l\'entretien',
    description_en: 'Practice real Japanese interview questions with an AI interviewer from a top automotive company. Receive real-time keigo correction and scoring.',
    description_fr: 'Pratiquez de vraies questions d\'entretien en japonais avec un recruteur IA d\'une grande entreprise automobile.',
    aiRole_en: 'Senior Interviewer, Automotive Company',
    aiRole_fr: 'Recruteur senior, entreprise automobile',
    accentColor: 'violet',
    icon: '💼',
    hint_en: 'Answer with keigo: 「〜でございます」「〜と思っております」',
    hint_fr: 'Répondez avec keigo: 「〜でございます」「〜と思っております」',
  },
  daily: {
    id: 'daily',
    title_en: 'Daily Conversation',
    title_fr: 'Conversation quotidienne',
    subtitle_en: '日常会話',
    subtitle_fr: 'Conversation de tous les jours',
    description_en: 'Chat with a Japanese colleague at the office — morning greetings, standup, lunch, after-work. Natural workplace Japanese.',
    description_fr: 'Discutez avec un collègue japonais au bureau — salutations, standup, déjeuner, après le travail.',
    aiRole_en: 'Japanese Colleague',
    aiRole_fr: 'Collègue japonais',
    accentColor: 'amber',
    icon: '☕',
    hint_en: 'Try: 「お疲れ様です！今日のスタンドアップはどうでしたか？」',
    hint_fr: 'Essayez: 「お疲れ様です！今日のスタンドアップはどうでしたか？」',
  },
  technical: {
    id: 'technical',
    title_en: 'Technical Discussion',
    title_fr: 'Discussion technique',
    subtitle_en: '技術的な話し合い',
    subtitle_fr: 'Débat technique',
    description_en: 'Discuss RTOS, CAN bus, debugging workflows, and embedded architectures in Japanese. Build the vocabulary you need for Japanese engineering teams.',
    description_fr: 'Discutez de RTOS, bus CAN, flux de débogage et architectures embarquées en japonais.',
    aiRole_en: 'Senior Embedded Engineer',
    aiRole_fr: 'Ingénieur embarqué senior',
    accentColor: 'blue',
    icon: '⚙️',
    hint_en: 'Try: 「このRTOSのタスク優先度について説明します。」',
    hint_fr: 'Essayez: 「このRTOSのタスク優先度について説明します。」',
  },
};

export const OPENING_LINES: Record<ScenarioId, string> = {
  jikoshoukai: 'はじめまして！自己紹介の練習をしましょう。まず、日本語で挨拶から始めてください。例えば、「はじめまして、〇〇と申します。」のように自己紹介してみてください。',
  interview: 'よろしくお願いします。本日は面接にお越しいただきありがとうございます。では、まず自己紹介をお願いできますか？',
  daily: 'おはようございます！今日もよろしくお願いします。昨日のコードレビューはどうでしたか？',
  technical: 'こんにちは！今日は組込みシステムについて日本語で話しましょう。今のプロジェクトについて教えていただけますか？',
};
